### PR TITLE
 Add New YNO games to discordRpcUtils

### PR DESCRIPTION
**Pull request by foundationkitty**
* Add Oneshot, If, and Unnacomplished to discordRpcUtils

NOTE: This is not intended to be merged unless the icons for the above games are added to the Discord RPC application. Playing one of the games above will throw an annoying error about a missing asset if you close the window with them running due to the missing asset. If said Discord application is no longer accessible by the new fork owner this should probably be redone at some point...

### CODE REVIEW

**Comment by aguish** [comment]
We could package the icons for each game locally, but I'll try to see why it might've broken first. From the first glance it gets the icon for the games from yno website.

**Comment by aguish** [comment]
I have decided to rewrite the whole Discord RPC section, when I make a commit, I'll let you know to review it and try it.

**Comment by aguish** [comment]
Please review.

**Comment by foundationkitty** [comment]
4053fd9 has no issues building on Windows on my end. Did not test Linux. 

Games added manually via this pr now show an icon, though not a fan of the change from character face icons to doors, especially with it being off center... not too sure how the old version was pulling the icons, is there an easy way we could still do this post rpc changes?

before

after

I personally like the edit from "Disconnected" to "Going to bed...", though this gives me the idea to implement the ability to custom set this either thru a config file or in the interface somehow.

Thoughts?

**Comment by foundationkitty** [comment]
As an additional thought, the character face icons are the favicon, would it be feasible to just pull that? I see the comment you threw in, I did a quick skim thru on the yno github repos and couldn't find where they are stored. Will dig a bit deeper later if needed.

**Comment by aguish** [comment]
Discord RPC doesn't support reading or using ico files as imageLargeKey or smallKey, before it was done by directly uploaded the icons to the discord developer portal or you could alternatively upload them to a third party host or have them locally saved. I dont' find any of these solutions good at all, so I decided to just use doors for now, but if you have any better ideas let me know.

**Comment by foundationkitty** [comment]
Moot with RPC changes

**Comment by roxwize** [comment]
I hope it's ok if I give my two cents. I'm mostly against the changes made to the RPC, the change from the face to the blurry doors (and also the improper capitalization of YNOproject) bugs me. If manually uploading icons to the developer portal was needed to get the old version to work properly then I would personally be okay with that; although you're the one maintaining the application so I imagine it is different for you.

Also since the application is running on the user's computer and is not limited to being a website could you not use some image manipulation tool like ImageMagick to convert the ico to a PNG? I don't know how Electron changes this but there should be something available that could make the website icons RPC-friendly. I could also ask the YNOproject devs if they'd be okay with also hosting the favicons as PNG files alongside the ICO versions as I don't think that's an uncommon thing for websites to do.

**Comment by foundationkitty** [comment]
I agree with changing the icons back to faces from doors, finding a better solution to this is something I’d like to work on when my schedule allows.

**Comment by affectioned** [comment]
> Also since the application is running on the user's computer and is not limited to being a website could you not use some image manipulation tool like ImageMagick to convert the ico to a PNG? I don't know how Electron changes this but there should be something available that could make the website icons RPC-friendly. I could also ask the YNOproject devs if they'd be okay with also hosting the favicons as PNG files alongside the ICO versions as I don't think that's an uncommon thing for websites to do.
Interesting points mostly abouy the ImageMagick and having it locally saved in local app data maybe?

**Comment by foundationkitty** [comment]
https://github.com/datvm/PNG2ICOjs

We could use something like this perchance?

**Pull request closed without merging**
